name: Publish

on:
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: macos-latest
            name: darwin-arm64
            target: arm64
          - runner: macos-latest
            name: darwin-x64
            target: x64
          - runner: ubuntu-24.04-arm
            name: linux-arm64
            target: arm64
          - runner: ubuntu-latest
            name: linux-x64
            target: x64
          - runner: windows-11-arm
            name: win32-arm64
            target: arm64
          - runner: windows-latest
            name: win32-x64
            target: x64
    name: Build on ${{ matrix.platform.runner }} for ${{ matrix.platform.name }} (${{ matrix.platform.target }})
    runs-on: ${{ matrix.platform.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: pnpm install --ignore-scripts

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: pnpm build

      - name: Test Binding
        run: pnpm test:release-binding

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.platform.name }}
          path: |
            build/Release/rocksdb-js.node
          if-no-files-found: error

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Setup dependencies
        uses: ./.github/actions/setup-deps
        with:
          gh-token: ${{ secrets.GH_TOKEN }}

      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          path: artifacts

      - name: List artifacts
        run: ls -la artifacts

      - name: Publish rocksdb-js platform specific bindings to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          TAG: ${{ github.event.release.prerelease && 'next' || 'latest' }}
        run: node scripts/publish.mjs

      # - name: Publish rocksdb-js to npm
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: npm publish --tag ${{ github.event.release.prerelease && 'next' || 'latest' }}
